### ISSUE TITLE
Grip pub control & Grip pub control client - what is the difference ?

### ISSUE THREAD

**Issue by zkrhm** [fanout/go-gripcontrol#2]

**Comment by jkarneges** [comment]
Hi,

PubControlClient publishes to a single GRIP service. PubControl aggregates multiple PubControlClients so you can publish to multiple services at once (e.g. multiple Pushpin instances).

**Comment by zkrhm** [comment]
hi @jkarneges thanks for superfast response. can I tried this library without jwt? I get following error when try to compile : 

```
vendor/github.com/fanout/go-pubcontrol/pubcontrolclient.go:98:25: invalid operation: token.Claims[k] (type jwt.Claims does not support indexing)
vendor/github.com/fanout/go-pubcontrol/pubcontrolclient.go:101:25: invalid operation: token.Claims["exp"] (type jwt.Claims does not support indexing)
```

i trace it , on go-jwt page says it because of they updating the library.

**Comment by jkarneges** [comment]
Thanks for the report! Will follow up on the other issue you posted, about making a release.
